### ISSUE TITLE
scoped should be marked unsafe (As it can be used to cause unsafety)

### ISSUE THREAD

**Issue by thepowersgang** [arcnmx/thread-scoped-rs#1]
As pointed out by Quxxy on #rust (https://botbot.me/mozilla/rust/2015-07-22/?msg=45229283&page=15) thread::scoped should be marked as unsafe, as (although it takes a bit of effort, and intent to do so), it can be used to cause memory unsafety.

**Comment by arcnmx** [comment]
Eh, fine. It's the

> although it takes a bit of effort, and intent to do so

part that makes me hate doing this, but I'll cave.

**Comment by thepowersgang** [comment]
I feel similar - But, that's the rules of unsafe. If you can do something wrong and cause memory unsafety with an interface, that interface should be marked as unsafe.

**Comment by arcnmx** [comment]
If your intent is to cause memory unsafety, you don't need `scoped()` to do that. `unsafe` exists for a reason >_>

I'd be more okay with it if `unsafe` were usable with arbitrary expressions, and not just blocks.

`unsafe scoped(...)` isn't so bad, but `unsafe { scoped(...) }` is ugly as all hell. Actually, has that ever been discussed?
