### ISSUE TITLE
Types are different from std

### ISSUE THREAD

**Issue by yongqli** [arcnmx/thread-scoped-rs#2]
I'm trying to use this crate as a replacement for the function from std, but the type signature is different.

`std::thread`: `pub fn scoped<'a, T, F>(f: F) -> JoinGuard<'a, T> 
where T: Send + 'a, F: FnOnce() -> T, F: Send + 'a`

`thread_scoped`: `pub unsafe fn scoped<'a, T, F>(f: F) -> JoinGuard<'a, T> where T: Send + 'static, F: FnOnce() -> T, F: Send + 'a`

`T` being `Send + 'static` is a problem for me, as my `f` is returning a pointer into the argument of `f`. This forces the argument to `f` to be `'static', which I do not want.

**Comment by arcnmx** [comment]
Thanks, I forgot I'd changed that. I didn't like it because it requires extra allocations to support (at least that's the only way I'm aware of implementing it), but done!
